# Generated by Django 5.2 on 2025-12-14 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_remove_cartitem_color_variant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_variant',
            new_name='product',
        ),
    ]
