# Generated by Django 5.2 on 2025-12-09 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_remove_category_cat_image_category_parent'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='product_image_back',
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_front',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(limit_choices_to={'parent__isnull': True}, on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory', to='categories.category'),
        ),
    ]
