# Generated by Django 5.2 on 2025-12-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_productvariant_price_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image_back',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product_image_back',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
