# Generated by Django 5.2 on 2025-12-13 15:00

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productcolorvariant_productsizevariant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolorvariant',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', validators=[products.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='productcolorvariant',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', validators=[products.models.validate_image]),
        ),
    ]
