# Generated by Django 5.2 on 2025-12-12 15:30

from django.db import migrations
from django.utils.text import slugify 

def fill_slugs(apps, schema_editor):
    Category = apps.get_model('categories', 'Category')
    for cat in Category.objects.all():
        if not cat.slug:
            cat.slug = slugify(cat.category_name)
            cat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_category_slug'),
    ]

    operations = [
        migrations.RunPython(fill_slugs),
    ]
