# Generated by Django 5.2 on 2025-12-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
